# Generated by Django 3.0.7 on 2020-06-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='time',
        ),
    ]
